name: homeworkplanner
description: Simple homework planning system for students
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  date_field: ^3.0.5
  file_picker: ^5.2.10
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
