name: homeworkplanner
description: Simple homework planning system for students
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  build_runner: ^2.3.3
  carousel_slider: ^4.2.1
  date_field: ^3.0.5
  dynamic_color: ^1.6.6
  file_picker: ^5.2.10
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  intl: ^0.18.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0
  supabase_flutter: ^2.3.4
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
